module ATProto
  module RequestUtils
    extend T::Sig

    include Kernel

    def self?.at_uri: (::String url, ?::String atp_host) -> untyped
  end
end

module ATProto
  CID: ::Skyfall::CID

  module AtUriParser
    extend T::Sig

    extend RequestUtils

    Rule: untyped

    def self.parse: (untyped url, untyped rulesets, ?pds: ::String) -> (untyped | nil)

    def self.create_rule: (untyped pattern) { () -> untyped } -> untyped

    RuleSets: ::Array[untyped]
  end

  class AtUri < T::Struct
    extend T::Sig

    def resolve: (?pds: ::String) -> untyped

    def to_s: () -> ::String
  end
end
