# typed: true
module ATProto
  class Repo
    class Collection < T::Struct
      include RequestUtils

      include Enumerable

      extend T::Sig

      def list: (?::Integer limit) -> untyped

      def list_all: () -> untyped

      def to_uri: () -> ::String

      def to_s: () -> untyped

      def []: (untyped rkey) -> untyped

      def each: () { () -> untyped } -> untyped
    end
  end
end
