# typed: false
module ATProto
  class Record < T::Struct
    extend T::Sig

    extend T::Sig

    extend RequestUtils

    def self.from_hash: (untyped json_hash) -> (nil | untyped)

    def self.from_uri: (untyped uri, ?::String pds) -> untyped

    def self.create: (untyped content_hash, untyped session, ?untyped? rkey) -> (nil | untyped)

    def refresh: (?::String pds) -> untyped

    def put: (untyped session) -> untyped

    def delete: (untyped session) -> untyped

    def to_write: (?::Symbol type) -> untyped

    def ==: (untyped other) -> untyped
  end
end
