module ATProto
  Credentials: untyped

  class Session
    include RequestUtils

    extend T::Sig

    attr_reader pds: untyped

    attr_reader access_token: untyped

    attr_reader refresh_token: untyped

    attr_reader did: untyped

    attr_reader xrpc: untyped

    def initialize: (untyped credentials, ?bool should_open) -> void

    def open!: () -> untyped

    def refresh!: () -> untyped

    def get_session: () -> untyped

    def delete!: () -> untyped
  end
end

module ATProto
  class TokenSession < Session
    extend T::Sig

    def initialize: (untyped token, ?::String pds) -> void

    def open!: () -> untyped
  end
end
