# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/Atmosfire/all/Atmosfire.rbi
#
# Atmosfire-0.0.1

module Atmosfire
end
class Atmosfire::Record < Struct
  def cid; end
  def cid=(_); end
  def collection; end
  def collection=(_); end
  def content; end
  def content=(_); end
  def delete(session); end
  def self.[](*arg0); end
  def self.create(content_hash, session); end
  def self.from_hash(json_hash); end
  def self.from_uri(uri, pds = nil); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def timestamp; end
  def timestamp=(_); end
  def update(session); end
  def uri; end
  def uri=(_); end
  extend T::Sig
end
