# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/base32/all/base32.rbi
#
# base32-0.3.4

module Base32
  def self.chunks(str, size); end
  def self.decode(str); end
  def self.encode(str); end
  def self.random_base32(length = nil, padding = nil); end
  def self.table; end
  def self.table=(table); end
  def self.table_valid?(table); end
end
class Base32::Chunk
  def decode; end
  def encode; end
  def initialize(bytes); end
end
