# typed: false
module ATProto
  module DID
    class Document
      extend T::Sig

      attr_reader context: untyped

      attr_reader id: untyped

      attr_reader alsoKnownAs: untyped

      attr_reader verificationMethod: untyped

      attr_reader service: untyped

      def initialize: (untyped json_doc) -> void
    end

    class VerificationMethod
      extend T::Sig

      attr_reader id: untyped

      attr_reader type: untyped

      attr_reader controller: untyped

      attr_reader publicKeyMultibase: untyped

      def initialize: (untyped data) -> void
    end

    class Service
      attr_accessor id: untyped

      attr_accessor type: untyped

      attr_accessor serviceEndpoint: untyped

      def initialize: (untyped data) -> void
    end

    class PLC < T::Struct
      extend T::Sig
    end
  end
end
